### ISSUE TITLE
Flughöhe/Entfernung 

### ISSUE THREAD

**Issue by wunderbaum** [toblum/was_fliegt_da#1]
Hallo,
Der Skill ist wirklich klasse.  Allerdings wird die Entfernung nicht ausgerechnet. Ein Flugzeug in 11km Höhe kann ja nicht 1km Entfernt sein. Da fehlt ein bisschen Pythagoras vermute ich.

**Comment by toblum** [comment]
Hi @wunderbaum,

danke für deine Rückmeldung. Die Entfernung ist immer "über Grund" gerechnet, also nicht die Luftlinie. Die Daten entsprechen dem, was du hier siehst:
https://global.adsbexchange.com/VirtualRadar/desktop.html

Viele Grüße
Tobias

**Comment by wunderbaum** [comment]
Hallo Tobias,

soweit ist mir da klar. Auf der Karte ist diese Angabe "über Grund" auch sinnvoll.

Wenn ich aus dem Fenster schaue möchte ich gern wissen, wie weit das Flugzeug wirklich weg ist und nicht vor meinem geistigen Auge die Karte sehen.

Und diese ewig lange Intro, kann man das wenigstens konfigurierbar machen?


Viele liebe Grüße!


________________________________

**Comment by toblum** [comment]
Hallo @wunderbaum,

ich glaube, die Angabe der direkten Entfernung wäre für die meisten Nutzer eher irritierend, da in den bekannten Diensten ja immer der Entfernung über Grund angegeben wird. Vielleicht kann ich aber beide Werte ansagen.
Den Introsatz musste ich ergänzen, weil der Skill ohne Intro nicht die Zertifizierung, wegen Verstoß gegen die Voicedesign-Guidelines, bestanden hatte. Ich probiere ihn aber jetzt nachträglich etwas zu kürzen.

Gruß
Tobias

**Comment by wunderbaum** [comment]
Hi,

ach, das schreibt Amazon so vor das da jedesmal ein Sermon runtergebetet wird, beim Abfallkalender ist das nämlich ähnlich. Wenn ich etwas starte weiss ich doch das ichs aufgerufen habe.... Die sind schon schräg drauf.  Bis das durch ist ist der Flieger meist schon weit weg.

Mit der Entfernung über Grund ist das eine Sache wo man sicher trefflich streiten kann 😊

Versuch doch mal die errechnete Entfernung als "Sichtentfernung" oder so mit auszugeben.


Dein Skill ist einer der wenigen wirklich sinnvollen Skills inmitten dieses ganzen Skillmists, muss man echt mal sagen, Es wundert mich das es bisher nur 3 Bewertungen gibt.


Weiter so!


________________________________

**Comment by toblum** [comment]
Hallo!

Im Detail wird es nicht vorgeschrieben, aber es gibt Beispiele nach denen verfahren werden soll, sonst kommt der Skill nicht durch die Zertifizierung. Ich habe da auch mehrere Runden drehen müssen, bis er das OK bekam. Ich habe die Texte nun aber etwas gekürzt.
Aktuell ist er wieder in der Zertifizierung, da ich Englisch ergänzt habe. Aktuell bin ich in Runde zwei. Das ist immer etwas mühsam.
Ich wollte auch noch die Möglichkeit ergänzen, Details zu einem Flug abzufragen, z.B. Flugzeugdetails. Dort könnte man auch noch die Sichtentfernung ergänzen. das merke ich mir. Aber ein nach dem Anderen.

Danke für dein Feedback. 

Viele Grüße
Tobias

**Comment by wunderbaum** [comment]
Hi,


immerhin hast Du Chancen die Alexa-Socken zu bekommen 😊


Und vergiss das Projekt mit den WS2812-LEDs nicht 😊




________________________________

**Comment by toblum** [comment]
Letzen Monat gabs angeblich sogar nen Hoodie, aber davon hab ich seitdem nichts mehr gehört.

So many projects, so little time. :-)
